# Generated by Django 2.2 on 2019-08-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='user_msg',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
